name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你想要触发部署的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build the project
      run: |
        source venv/bin/activate
        export FLASK_APP=app.py
        flask run --host=0.0.0.0 --port=8000 &
        sleep 5  # 等待服务器启动
        pytest tests  # 如果有测试的话
        deactivate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # 假设你已经有一个构建目录
